[project]
name = "rl-sim2real"
version = "0.1.0"
requires-python = ">=3.11, <3.13"
dependencies = [
    "gymnasium[mujoco]>=1.3.0",
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.1",
    "numpy>=1.26.0,<2.0.0",
    "panda-gym",
    "pandas>=3.0.5",
    "pyyaml>=6.0.3",
    "seaborn>=0.13.2",
    "stable-baselines3[extra]>=2.0.0",
    "torch>=2.13.0",
]

[tool.uv.sources]
panda-gym = { path = "part2/panda-gym", editable = true }
