algo: sac
timesteps: 500_000
n_envs: 8

# SAC Hyperparameters
hyperparams:
  learning_rate: 0.001
  buffer_size: 1_000_000
  batch_size: 1024
  train_freq: 64
  gradient_steps: 64
  ent_coef: "auto_0.1"
  gamma: 0.95
  tau: 0.005
  device: "cpu"
  ent_coef: "auto_0.1"
  policy_kwargs: 
    net_arch: [256, 256, 256]